[pytest]
#todas las pruebas
python_files = test_*.py
#todas las funciones
python_functions = test_*
#se genera un reporte con detalle de la prueba y el report html
addopts = -v --html=reports/reporte.html --self-contained-html

